name: test

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.15
      uses: actions/setup-java@v1
      with:
        java-version: 1.15
    
    - name: Test
      run: gradle test
